using System.Globalization;

using GumpStudio.Core.Document;
using GumpStudio.Core.Elements;
using GumpStudio.Core.Primitives;

namespace GumpStudio.Core.Layout;

/// <summary>The result of parsing layout text, with anything that looked wrong.</summary>
/// <param name="Layout">The commands and strings that were understood.</param>
/// <param name="Warnings">
/// One line per thing skipped or guessed at. Parsing never throws on unexpected
/// input: a capture is something someone pasted, and reporting what was dropped
/// is far more useful than refusing the whole paste over one unknown command.
/// </param>
public sealed record LayoutParseResult(GumpLayout Layout, IReadOnlyList<string> Warnings)
{
    /// <summary>True when nothing at all was recognised.</summary>
    public bool IsEmpty => Layout.Commands.Count == 0;
}

/// <summary>
/// Reads the client's layout text back into commands.
/// </summary>
/// <remarks>
/// <para>
/// The inverse of <see cref="LayoutStringWriter"/>, and the front half of
/// importing a gump captured off the wire. Packet-sniffing tools dump the layout
/// string a server sent, which is the same grammar this writes — so a capture can
/// be pasted straight in.
/// </para>
/// <para>
/// It is deliberately lenient about shape, because captures are not generated by
/// one tool. Braces around each command are optional, the <c>[layout]</c> and
/// <c>[text]</c> markers are optional, several commands may share a line,
/// comments and blank lines are skipped, and runs of whitespace inside a command
/// are treated as one separator — real captures contain all of these.
/// </para>
/// </remarks>
public static class LayoutStringParser
{
    /// <summary>
    /// Whether text looks like a gump layout, for deciding whether to offer an import.
    /// </summary>
    /// <remarks>
    /// Requires a recognised command rather than just a brace, so an ordinary
    /// snippet of code on the clipboard is not mistaken for a gump.
    /// </remarks>
    public static bool LooksLikeLayout(string? text)
    {
        if (string.IsNullOrWhiteSpace(text))
        {
            return false;
        }

        if (text.Contains("[layout]", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        int recognised = 0;

        foreach (string command in Commands(text))
        {
            if (Verb(command) is { Length: > 0 } verb && Known.Contains(verb))
            {
                recognised++;

                if (recognised >= 2)
                {
                    return true;
                }
            }
        }

        return false;
    }

    /// <summary>Parses layout text into commands and strings.</summary>
    public static LayoutParseResult Parse(string? text)
    {
        List<LayoutCommand> commands = [];
        List<LayoutText> texts = [];
        List<(int Line, string Reason)> problems = [];
        GumpProperties properties = new();

        Section section = Section.Layout;
        int page = 0;
        int line = 0;

        foreach (string raw in (text ?? string.Empty).Split('\n'))
        {
            line++;

            string trimmed = raw.Trim().TrimEnd('\r').Trim();

            if (trimmed.Length == 0 || trimmed.StartsWith("//", StringComparison.Ordinal))
            {
                ReadHeader(trimmed, properties);

                continue;
            }

            if (SectionOf(trimmed) is { } next)
            {
                section = next;

                continue;
            }

            if (section == Section.Text)
            {
                texts.Add(new LayoutText(Unwrap(trimmed), TextRole.Label));

                continue;
            }

            foreach (string command in Commands(trimmed))
            {
                if (ReadCommand(command, commands, properties, ref page) is { } reason)
                {
                    problems.Add((line, reason));
                }
            }
        }

        return new LayoutParseResult(new GumpLayout(properties, commands, texts), Summarise(problems));
    }

    /// <summary>
    /// One warning per distinct problem, however many lines had it.
    /// </summary>
    /// <remarks>
    /// A capture can carry dozens of the same unusable command — the Enhanced
    /// Client ones especially — and a list with forty near-identical lines in it
    /// buries the one that matters.
    /// </remarks>
    private static List<string> Summarise(List<(int Line, string Reason)> problems)
    {
        List<string> warnings = [];
        Dictionary<string, (int First, int Count)> seen = new(StringComparer.Ordinal);

        foreach ((int line, string reason) in problems)
        {
            seen[reason] = seen.TryGetValue(reason, out (int First, int Count) at)
                ? (at.First, at.Count + 1)
                : (line, 1);
        }

        foreach ((string reason, (int first, int count)) in seen)
        {
            warnings.Add(count == 1
                ? $"Line {first}: {reason}"
                : $"Line {first} and {count - 1} more: {reason}");
        }

        return warnings;
    }

    /// <summary>
    /// Reads what the header comment says about the gump itself.
    /// </summary>
    /// <remarks>
    /// Capture tools write a line like
    /// <c>// Gump 0x1CC at (50, 50) — serial 043CAD798</c>. The id and position
    /// are worth keeping; the serial belongs to the session that captured it and
    /// means nothing in a saved design.
    /// </remarks>
    private static void ReadHeader(string line, GumpProperties properties)
    {
        int at = line.IndexOf(" at (", StringComparison.OrdinalIgnoreCase);

        if (at < 0 || !line.Contains("gump", StringComparison.OrdinalIgnoreCase))
        {
            return;
        }

        int close = line.IndexOf(')', at);

        if (close > at)
        {
            string[] parts = line[(at + 5)..close].Split(',');

            if (parts.Length == 2
                && TryNumber(parts[0].Trim(), out int x)
                && TryNumber(parts[1].Trim(), out int y))
            {
                properties.Location = new GumpPoint(x, y);
            }
        }

        // "Gump 0x1CC" — the id the server sent it under.
        string[] words = line.Split(' ', StringSplitOptions.RemoveEmptyEntries);

        for (int i = 0; i < words.Length - 1; i++)
        {
            if (words[i].Equals("gump", StringComparison.OrdinalIgnoreCase)
                && TryNumber(words[i + 1], out int id))
            {
                properties.TypeId = id;

                return;
            }
        }
    }

    /// <summary>Reads one command, returning a warning when it could not be used.</summary>
    private static string? ReadCommand(
        string command, List<LayoutCommand> commands, GumpProperties properties, ref int page)
    {
        string verb = Verb(command);

        if (verb.Length == 0)
        {
            return null;
        }

        // Everything from the first '@' is an argument blob, not a number.
        int at = command.IndexOf('@', StringComparison.Ordinal);
        string arguments = at >= 0 ? Arguments(command[at..]) : string.Empty;
        string head = at >= 0 ? command[..at] : command;

        string[] parts = head.Split(
            [' ', '\t'], StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);

        int[] numbers = new int[parts.Length - 1];

        for (int i = 1; i < parts.Length; i++)
        {
            if (!TryNumber(parts[i], out numbers[i - 1]))
            {
                return $"'{verb}' has a non-numeric argument '{parts[i]}'; skipped.";
            }
        }

        CommandOrigin origin = new(commands.Count, page, IsPrimary: true, string.Empty, string.Empty);

        switch (verb)
        {
            case "page" when numbers.Length >= 1:
                page = numbers[0];
                commands.Add(new PageCommand(origin with { PageIndex = page }, page));

                return null;

            case "group" when numbers.Length >= 1:
                commands.Add(new GroupCommand(origin, numbers[0]));

                return null;

            case "endgroup":
                commands.Add(new EndGroupCommand(origin));

                return null;

            case "nomove":
                properties.Movable = false;

                return null;

            case "noclose":
                properties.Closable = false;

                return null;

            case "nodispose":
                properties.Disposable = false;

                return null;

            case "mastergump" when numbers.Length >= 1:
                properties.MasterGumpId = numbers[0];

                return null;

            case "toggleupperwordcase":
                properties.UpperWordCase = true;

                return null;

            case "togglecroppedtext":
                properties.CroppedText = true;

                return null;

            case "echandleinput":
                properties.EnhancedClientInput = true;

                return null;

            case "resizepic" when numbers.Length >= 5:
                commands.Add(new ResizePicCommand(
                    origin, numbers[0], numbers[1], numbers[2], numbers[3], numbers[4]));

                return null;

            case "checkertrans" when numbers.Length >= 4:
                commands.Add(new CheckerTransCommand(
                    origin, numbers[0], numbers[1], numbers[2], numbers[3]));

                return null;

            case "gumppictiled" when numbers.Length >= 5:
                commands.Add(new GumpPicTiledCommand(
                    origin, numbers[0], numbers[1], numbers[2], numbers[3], numbers[4]));

                return null;

            // The client accepts a bare hue on gumppic as well as the explicit
            // hued form, and both mean a full tint.
            case "gumppic" when numbers.Length >= 3:
            case "gumppichued" when numbers.Length >= 4:
                commands.Add(new GumpPicCommand(
                    origin,
                    numbers[0],
                    numbers[1],
                    numbers[2],
                    numbers.Length >= 4 ? numbers[3] : 0,
                    PartialHue: false));

                return null;

            case "gumppicphued" when numbers.Length >= 4:
                commands.Add(new GumpPicCommand(
                    origin, numbers[0], numbers[1], numbers[2], numbers[3], PartialHue: true));

                return null;

            case "picinpic" when numbers.Length >= 7:
            case "picinpichued" when numbers.Length >= 8:
            case "picinpicphued" when numbers.Length >= 8:
                commands.Add(new PicInPicCommand(
                    origin,
                    numbers[0],
                    numbers[1],
                    numbers[2],
                    numbers[3],
                    numbers[4],
                    numbers[5],
                    numbers[6],
                    numbers.Length >= 8 ? numbers[7] : 0,
                    verb == "picinpicphued"));

                return null;

            case "tilepic" when numbers.Length >= 3:
            case "tilepichue" when numbers.Length >= 4:
                commands.Add(new TilePicCommand(
                    origin,
                    numbers[0],
                    numbers[1],
                    numbers[2],
                    numbers.Length >= 4 ? numbers[3] : 0));

                return null;

            case "tilepicasgumppic" when numbers.Length >= 6:
                commands.Add(new TileAsGumpPicCommand(
                    origin, numbers[0], numbers[1], numbers[2], numbers[3], numbers[4], numbers[5]));

                return null;

            case "text" when numbers.Length >= 4:
                commands.Add(new TextCommand(
                    origin, numbers[0], numbers[1], numbers[2], new TextRef(numbers[3])));

                return null;

            case "croppedtext" when numbers.Length >= 6:
                commands.Add(new CroppedTextCommand(
                    origin,
                    numbers[0],
                    numbers[1],
                    numbers[2],
                    numbers[3],
                    numbers[4],
                    new TextRef(numbers[5])));

                return null;

            // x y width height hue entryId textIndex [maxLength]
            case "textentry" when numbers.Length >= 7:
            case "textentrylimited" when numbers.Length >= 8:
                commands.Add(new TextEntryCommand(
                    origin,
                    numbers[0],
                    numbers[1],
                    numbers[2],
                    numbers[3],
                    numbers[4],
                    numbers[5],
                    new TextRef(numbers[6]),
                    numbers.Length >= 8 ? numbers[7] : 0));

                return null;

            case "htmlgump" when numbers.Length >= 7:
                commands.Add(new HtmlGumpCommand(
                    origin,
                    numbers[0],
                    numbers[1],
                    numbers[2],
                    numbers[3],
                    new TextRef(numbers[4]),
                    numbers[5] != 0,
                    numbers[6] != 0));

                return null;

            case "xmfhtmlgump" when numbers.Length >= 7:
                commands.Add(new XmfHtmlCommand(
                    origin,
                    numbers[0],
                    numbers[1],
                    numbers[2],
                    numbers[3],
                    numbers[4],
                    numbers[5] != 0,
                    numbers[6] != 0,
                    Color: 0,
                    Arguments: string.Empty));

                return null;

            case "xmfhtmlgumpcolor" when numbers.Length >= 8:
                commands.Add(new XmfHtmlCommand(
                    origin,
                    numbers[0],
                    numbers[1],
                    numbers[2],
                    numbers[3],
                    numbers[4],
                    numbers[5] != 0,
                    numbers[6] != 0,
                    numbers[7],
                    Arguments: string.Empty));

                return null;

            // Its slots are genuinely not the colour form's: the flags come
            // before the colour and the cliloc id comes last.
            case "xmfhtmltok" when numbers.Length >= 8:
                commands.Add(new XmfHtmlCommand(
                    origin,
                    numbers[0],
                    numbers[1],
                    numbers[2],
                    numbers[3],
                    numbers[7],
                    numbers[4] != 0,
                    numbers[5] != 0,
                    numbers[6],
                    arguments));

                return null;

            case "button" when numbers.Length >= 7:
            case "buttontileart" when numbers.Length >= 11:
                commands.Add(Button(origin, verb, numbers));

                return null;

            case "checkbox" when numbers.Length >= 6:
                commands.Add(new CheckboxCommand(
                    origin,
                    numbers[0],
                    numbers[1],
                    numbers[2],
                    numbers[3],
                    numbers[4] != 0,
                    numbers[5]));

                return null;

            case "radio" when numbers.Length >= 6:
                commands.Add(new RadioCommand(
                    origin,
                    numbers[0],
                    numbers[1],
                    numbers[2],
                    numbers[3],
                    numbers[4] != 0,
                    numbers[5]));

                return null;

            case "tooltip" when numbers.Length >= 1:
                commands.Add(new TooltipCommand(origin, numbers[0], arguments));

                return null;

            case "itemproperty" when numbers.Length >= 1:
                commands.Add(new ItemPropertyCommand(origin, numbers[0]));

                return null;

            default:
                if (Known.Contains(verb))
                {
                    return $"'{verb}' has {numbers.Length} arguments, which is too few; skipped.";
                }

                // The Enhanced Client has its own kr_ commands, which the classic
                // client ignores and which carry no geometry worth keeping — a
                // capture from an EC session is full of them.
                return verb.StartsWith("kr_", StringComparison.Ordinal)
                    ? $"Enhanced Client command '{verb}'; ignored."
                    : $"Unknown command '{verb}'; skipped.";
        }
    }

    /// <summary>
    /// A button, whose three trailing slots are quit, target page and reply id.
    /// </summary>
    /// <remarks>
    /// A page button does not quit and carries its target in the page slot; a
    /// reply button quits and carries its id in the return slot. Reading them the
    /// other way round is the defect the 1.8 exporter shipped with.
    /// </remarks>
    private static ButtonCommand Button(CommandOrigin origin, string verb, int[] n)
    {
        bool isPage = n[4] == 0;

        ButtonTile? tile = verb == "buttontileart"
            ? new ButtonTile(n[7], n[8], n[9], n[10])
            : null;

        return new ButtonCommand(
            origin,
            n[0],
            n[1],
            n[2],
            n[3],
            isPage ? ButtonKind.Page : ButtonKind.Reply,
            isPage ? n[5] : n[6],
            tile,
            string.Empty);
    }

    /// <summary>
    /// The substitution arguments, without the delimiters the layout string uses.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The model stores them separated by <c>@</c>, which is the form they arrive
    /// in. Captures are inconsistent about how many delimiters surround the list:
    /// <c>@#1027027</c>, <c>@0@10</c> and <c>@@#1072325</c> all appear, and all
    /// three name their first argument first.
    /// </para>
    /// <para>
    /// So every leading and trailing delimiter is stripped, not just one. The
    /// client tokenises the list the way <c>strtok</c> does, running consecutive
    /// delimiters together, which is why a doubled <c>@@</c> does not mean an
    /// empty first argument — reading it as one left a cliloc whose only
    /// placeholder is <c>~1_TOKEN~</c> substituting nothing at all.
    /// </para>
    /// </remarks>
    private static string Arguments(string blob) => blob.Trim().Trim('@');

    /// <summary>Every command name that is understood, for detection and diagnostics.</summary>
    private static readonly HashSet<string> Known = new(StringComparer.Ordinal)
    {
        "page", "group", "endgroup",
        "nomove", "noclose", "nodispose",
        "mastergump", "toggleupperwordcase", "togglecroppedtext", "echandleinput",
        "resizepic", "checkertrans", "gumppictiled",
        "gumppic", "gumppichued", "gumppicphued",
        "picinpic", "picinpichued", "picinpicphued",
        "tilepic", "tilepichue", "tilepicasgumppic",
        "text", "croppedtext", "textentry", "textentrylimited",
        "htmlgump", "xmfhtmlgump", "xmfhtmlgumpcolor", "xmfhtmltok",
        "button", "buttontileart", "checkbox", "radio",
        "tooltip", "itemproperty",
    };

    private static string Verb(string command)
    {
        string trimmed = command.TrimStart();
        int end = trimmed.IndexOfAny([' ', '\t']);

        return (end < 0 ? trimmed : trimmed[..end]).ToLowerInvariant();
    }

    /// <summary>
    /// The commands on one line.
    /// </summary>
    /// <remarks>
    /// Braces are the usual form and several commands may share a line, but a
    /// capture that has stripped them is still readable — so a line with no
    /// braces at all is treated as a single command.
    /// </remarks>
    private static IEnumerable<string> Commands(string line)
    {
        bool braced = false;

        for (int i = 0; i < line.Length; i++)
        {
            if (line[i] != '{')
            {
                continue;
            }

            int close = line.IndexOf('}', i);

            if (close < 0)
            {
                break;
            }

            braced = true;

            string inner = line[(i + 1)..close].Trim();

            if (inner.Length > 0)
            {
                yield return inner;
            }

            i = close;
        }

        if (!braced)
        {
            string bare = line.Trim();

            if (bare.Length > 0 && !bare.StartsWith('['))
            {
                yield return bare;
            }
        }
    }

    /// <summary>Strips the braces a text entry is usually wrapped in.</summary>
    private static string Unwrap(string line)
    {
        string value = line.Trim();

        return value.StartsWith('{') && value.EndsWith('}')
            ? value[1..^1].Trim()
            : value;
    }

    private static Section? SectionOf(string line) => line.ToLowerInvariant() switch
    {
        "[layout]" => Section.Layout,
        "[text]" or "[data]" or "[strings]" => Section.Text,
        _ => null,
    };

    /// <summary>Reads a decimal or <c>0x</c>-prefixed value.</summary>
    private static bool TryNumber(string value, out int number)
    {
        string text = value.Trim();

        if (text.StartsWith("0x", StringComparison.OrdinalIgnoreCase))
        {
            return int.TryParse(
                text[2..], NumberStyles.HexNumber, CultureInfo.InvariantCulture, out number);
        }

        return int.TryParse(text, NumberStyles.Integer, CultureInfo.InvariantCulture, out number);
    }

    private enum Section
    {
        Layout,
        Text,
    }
}
